#!/usr/bin/env python3
"""Generate manuscript numbers and table bodies from the corrected CSV outputs."""
from pathlib import Path
import hashlib
import json
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data/revision/results"


def main():
    d = pd.read_csv(OUT / "all_specifications.csv")
    p = pd.read_csv(OUT / "primary_item_results.csv").set_index("lemma")
    controls = pd.read_csv(OUT / "control_recovery_by_specification.csv")
    macros = {}
    for item, name in [("each_other","Each"),("one_another","One")]:
        for field, suffix in [("d_pronoun","DP"),("d_compound","DC"),("delta","Delta"),("delta_percentile","Quantile")]:
            macros[name+suffix] = f"{p.loc[item,field]:.2f}"
    for role,name in [("pronoun_anchor","Pron"),("compound_anchor","Comp")]:
        z=p[p.role.eq(role)].delta
        macros[name+"DeltaMin"],macros[name+"DeltaMax"] = f"{z.min():.2f}",f"{z.max():.2f}"
    (OUT/"numbers.tex").write_text("% Generated by code/revision_tables.py; do not hand-edit.\n" +
        "\n".join(r"\newcommand{\Rev"+k+"}{"+v+"}" for k,v in macros.items())+"\n")
    rows=[]
    for item in ["she","everyone","each_other","one_another"]:
        z=p.loc[item]
        rows.append(r"\mention{"+item.replace("_"," ")+"} & "+" & ".join(f"{z[k]:.2f}" for k in ["d_pronoun","d_compound","delta","delta_percentile"])+r" \\")
    (OUT/"primary_table.tex").write_text("\n".join(rows)+"\n"+r"\bottomrule"+"\n")
    rows=[]
    for drop,label in [("none","All retained features"),("morph","Without morphology"),("synt","Without syntax"),("sem","Without semantics"),("phon","Without phonology")]:
        z=d.query("drop==@drop and pool=='full' and holdout=='item' and metric=='jaccard' and reference=='fixed_total' and role=='target'").set_index("lemma")
        c=controls.query("drop==@drop and pool=='full' and holdout=='item' and metric=='jaccard'").iloc[0]
        rows.append(label+f" & {int(z.features.iloc[0])} & "+" & ".join(f"{z.loc[item,'delta']:.2f}" for item in ["each_other","one_another"])+f" & {c.controls_correct}/{c.n_controls}"+r" \\")
    (OUT/"ablation_table.tex").write_text("\n".join(rows)+"\n"+r"\bottomrule"+"\n")
    coding=pd.read_csv(OUT/"coding_sensitivity.csv").query("metric=='jaccard'")
    rows=[]
    for op,label in [("delete_feature","Delete one feature"),("reverse_polarity","Reverse one feature's polarity"),("flip_target_cell","Flip one target cell")]:
        cells=[]
        for item in ["each_other","one_another"]:
            z=coding.query("operation==@op and lemma==@item").delta
            cells.append(f"{z.min():.2f}--{z.max():.2f}")
        rows.append(label+" & "+" & ".join(cells)+r" \\")
    (OUT/"coding_table.tex").write_text("\n".join(rows)+"\n"+r"\bottomrule"+"\n")
    examples=pd.read_csv(OUT/"illustrative_matrix.csv").set_index("lemma")
    rows=[]
    for item,z in examples.iterrows():
        rows.append(r"\mention{"+item.replace("_"," ")+"} & "+" & ".join(str(v) for v in z)+r" \\")
    (OUT/"example_table.tex").write_text("\n".join(rows)+"\n"+r"\bottomrule"+"\n")

    metadata = {"script_sha256": hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
                "analysis_metadata_sha256": hashlib.sha256((OUT/"run_metadata.json").read_bytes()).hexdigest(),
                "inputs": {p.name: hashlib.sha256(p.read_bytes()).hexdigest() for p in OUT.glob("*.csv")},
                "outputs": {p.name: hashlib.sha256(p.read_bytes()).hexdigest() for p in OUT.glob("*.tex")}}
    (OUT/"table_metadata.json").write_text(json.dumps(metadata,indent=2)+"\n")


if __name__=="__main__":
    main()
